development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  # url: <%= ENV['REDISCLOUD_URL'] %>
  url: <%= ENV['REDISTOGO_URL'] %>
  channel_prefix: speedbattles_production
